export const mockPackages = [
  {
    id: "1",
    title: "Aventura Tropical en Cancún",
    destination: "Cancún, México",
    image: "/cancun-beach-tropical-paradise.jpg",
    price: 899,
    duration: "5 días",
    rating: 4.8,
    reviews: 245,
    groupSize: "2-8 personas",
    featured: true,
    tags: ["Playa", "Todo Incluido", "Familia"],
  },
  {
    id: "2",
    title: "Escapada Romántica a París",
    destination: "París, Francia",
    image: "/paris-eiffel-tower-romantic.png",
    price: 1499,
    duration: "7 días",
    rating: 4.9,
    reviews: 189,
    groupSize: "2 personas",
    featured: true,
    tags: ["Ciudad", "Romántico", "Cultural"],
  },
  {
    id: "3",
    title: "Safari en Tanzania",
    destination: "Serengeti, Tanzania",
    image: "/tanzania-safari-wildlife.jpg",
    price: 2299,
    duration: "10 días",
    rating: 5.0,
    reviews: 98,
    groupSize: "4-12 personas",
    featured: false,
    tags: ["Aventura", "Naturaleza", "Safari"],
  },
  {
    id: "4",
    title: "Tour Cultural por Japón",
    destination: "Tokio, Kioto, Osaka",
    image: "/japan-temple-cherry-blossom.jpg",
    price: 1899,
    duration: "12 días",
    rating: 4.9,
    reviews: 156,
    groupSize: "6-15 personas",
    featured: true,
    tags: ["Cultural", "Ciudad", "Gastronómico"],
  },
  {
    id: "5",
    title: "Machu Picchu y Cusco",
    destination: "Cusco, Perú",
    image: "/machu-picchu-mountains.png",
    price: 1199,
    duration: "8 días",
    rating: 4.7,
    reviews: 203,
    groupSize: "4-10 personas",
    featured: false,
    tags: ["Aventura", "Historia", "Montaña"],
  },
  {
    id: "6",
    title: "Islas Griegas en Velero",
    destination: "Santorini, Mykonos",
    image: "/santorini-white-buildings.png",
    price: 1699,
    duration: "9 días",
    rating: 4.8,
    reviews: 134,
    groupSize: "2-6 personas",
    featured: false,
    tags: ["Playa", "Romántico", "Aventura"],
  },
]

export const mockExperiences = [
  {
    id: "exp-1",
    title: "Buceo en Arrecifes de Coral",
    location: "Cozumel, México",
    image: "/images/diving.png",
    price: 149,
    duration: "4 horas",
    rating: 4.9,
    reviews: 87,
    category: "Aventura",
  },
  {
    id: "exp-2",
    title: "Tour Gastronómico Nocturno",
    location: "Barcelona, España",
    image: "/barcelona-tapas-food-tour.jpg",
    price: 89,
    duration: "3 horas",
    rating: 4.7,
    reviews: 156,
    category: "Gastronómico",
  },
  {
    id: "exp-3",
    title: "Senderismo al Amanecer",
    location: "Alpes Suizos",
    image: "/swiss-alps-hiking-sunrise.jpg",
    price: 120,
    duration: "6 horas",
    rating: 5.0,
    reviews: 64,
    category: "Naturaleza",
  },
  {
    id: "exp-4",
    title: "Clase de Cocina Italiana",
    location: "Florencia, Italia",
    image: "/italian-cooking-class-pasta.png",
    price: 95,
    duration: "4 horas",
    rating: 4.8,
    reviews: 201,
    category: "Gastronómico",
  },
]

export const megaTravelOffers = [
  {
    id: "mega-1",
    title: "Mega Oferta Cancún",
    destination: "Cancún, México",
    image: "/cancun-beach-tropical-paradise.jpg",
    originalPrice: 1299,
    price: 799,
    discount: 38,
    duration: "7 días / 6 noches",
    rating: 4.9,
    reviews: 412,
    featured: true,
    tags: ["Todo Incluido", "Vuelo + Hotel", "Playa"],
    includes: ["Vuelo redondo", "Hotel 5 estrellas", "Alimentos", "Tours"],
  },
  {
    id: "mega-2",
    title: "Super Combo Europa",
    destination: "París + Roma + Madrid",
    image: "/paris-eiffel-tower-romantic.png",
    originalPrice: 2499,
    price: 1699,
    discount: 32,
    duration: "14 días / 13 noches",
    rating: 5.0,
    reviews: 287,
    featured: true,
    tags: ["Multi-ciudad", "Cultural", "Vuelos incluidos"],
    includes: ["Vuelos internos", "Hoteles 4 estrellas", "Desayunos", "Traslados"],
  },
  {
    id: "mega-3",
    title: "Caribe Total",
    destination: "Punta Cana",
    image: "/punta-cana-beach-resort.jpg",
    originalPrice: 1599,
    price: 999,
    discount: 37,
    duration: "5 días / 4 noches",
    rating: 4.8,
    reviews: 523,
    featured: true,
    tags: ["Resort 5 estrellas", "Todo Incluido", "Familiar"],
    includes: ["Vuelo directo", "Resort premium", "Bebidas ilimitadas", "Actividades"],
  },
]

export const popularDestinations = [
  { name: "Cancún", country: "México", image: "/cancun-beach-tropical-paradise.jpg", trips: 1250 },
  { name: "París", country: "Francia", image: "/paris-eiffel-tower-romantic.png", trips: 980 },
  { name: "Punta Cana", country: "Rep. Dominicana", image: "/punta-cana-beach-resort.jpg", trips: 856 },
  { name: "Miami", country: "Estados Unidos", image: "/miami-beach-skyline.jpg", trips: 742 },
  { name: "Barcelona", country: "España", image: "/barcelona-sagrada-familia.jpg", trips: 698 },
  { name: "Nueva York", country: "Estados Unidos", image: "/new-york-times-square.jpg", trips: 621 },
]

export const internationalPackages = [
  {
    id: "int-1",
    title: "Gran Tour Europeo",
    destination: "París, Roma, Barcelona, Ámsterdam",
    image: "/paris-eiffel-tower-romantic.png",
    price: 2899,
    duration: "15 días",
    rating: 5.0,
    reviews: 342,
    groupSize: "8-20 personas",
    continent: "Europa",
    featured: true,
    tags: ["Multi-ciudad", "Cultural", "Todo Incluido"],
  },
  {
    id: "int-2",
    title: "Maravillas de Asia",
    destination: "Tokio, Bangkok, Singapur",
    image: "/japan-temple-cherry-blossom.jpg",
    price: 3299,
    duration: "18 días",
    rating: 4.9,
    reviews: 267,
    groupSize: "10-25 personas",
    continent: "Asia",
    featured: true,
    tags: ["Cultural", "Gastronómico", "Aventura"],
  },
  {
    id: "int-3",
    title: "Safari Africano Premium",
    destination: "Kenia y Tanzania",
    image: "/tanzania-safari-wildlife.jpg",
    price: 4199,
    duration: "12 días",
    rating: 5.0,
    reviews: 189,
    groupSize: "6-12 personas",
    continent: "África",
    featured: true,
    tags: ["Safari", "Naturaleza", "Lujo"],
  },
  {
    id: "int-4",
    title: "Circuito por Sudamérica",
    destination: "Buenos Aires, Río, Lima, Cusco",
    image: "/machu-picchu-mountains.png",
    price: 2599,
    duration: "14 días",
    rating: 4.8,
    reviews: 298,
    groupSize: "8-16 personas",
    continent: "América del Sur",
    featured: false,
    tags: ["Multi-país", "Cultura", "Historia"],
  },
  {
    id: "int-5",
    title: "Islas del Mediterráneo",
    destination: "Grecia e Italia",
    image: "/santorini-white-buildings.png",
    price: 2199,
    duration: "10 días",
    rating: 4.9,
    reviews: 412,
    groupSize: "4-12 personas",
    continent: "Europa",
    featured: false,
    tags: ["Playa", "Romántico", "Cultural"],
  },
]

export const clientPhotos = [
  {
    id: "client-1",
    image: "/client-photo-beach-happy.jpg",
    alt: "Clientes felices en la playa",
    location: "Cancún, México",
  },
  {
    id: "client-2",
    image: "/client-photo-eiffel-tower.jpg",
    alt: "Pareja frente a Torre Eiffel",
    location: "París, Francia",
  },
  {
    id: "client-3",
    image: "/client-photo-safari.jpg",
    alt: "Familia en safari",
    location: "Tanzania",
  },
  {
    id: "client-4",
    image: "/client-photo-temple.jpg",
    alt: "Viajeros en templo japonés",
    location: "Kioto, Japón",
  },
  {
    id: "client-5",
    image: "/client-photo-group.jpg",
    alt: "Grupo de amigos viajando",
    location: "Barcelona, España",
  },
  {
    id: "client-6",
    image: "/client-photo-mountains.jpg",
    alt: "Pareja en Machu Picchu",
    location: "Cusco, Perú",
  },
]

export const socialTestimonials = [
  {
    id: "test-1",
    name: "María González",
    platform: "facebook",
    avatar: "/avatar-maria.jpg",
    rating: 5,
    date: "Hace 2 semanas",
    text: "¡Increíble experiencia! Koneex nos organizó el viaje perfecto a Cancún. Todo salió impecable, desde el vuelo hasta el hotel. Super recomendados 🌴✨",
    likes: 45,
  },
  {
    id: "test-2",
    name: "Carlos Ramírez",
    platform: "instagram",
    avatar: "/avatar-carlos.jpg",
    rating: 5,
    date: "Hace 1 mes",
    text: "Gracias a Koneex cumplí mi sueño de conocer París. La atención fue excepcional y los precios muy accesibles. Ya estoy planeando mi próximo viaje con ellos 🗼❤️",
    likes: 89,
  },
  {
    id: "test-3",
    name: "Ana López",
    platform: "facebook",
    avatar: "/avatar-ana.jpg",
    rating: 5,
    date: "Hace 3 semanas",
    text: "El mejor servicio de agencia de viajes que he usado. Nos ayudaron con todo el trámite de visa y nos consiguieron un paquete todo incluido increíble. 100% recomendados! 🎉",
    likes: 67,
  },
  {
    id: "test-4",
    name: "Roberto Méndez",
    platform: "instagram",
    avatar: "/avatar-roberto.jpg",
    rating: 5,
    date: "Hace 5 días",
    text: "Contraté un tour por Europa con Koneex y fue la mejor decisión. Todo perfectamente organizado, guías excepcionales. Volveré a viajar con ellos sin dudarlo! 🌍✈️",
    likes: 123,
  },
  {
    id: "test-5",
    name: "Laura Sánchez",
    platform: "facebook",
    avatar: "/avatar-laura.jpg",
    rating: 5,
    date: "Hace 1 semana",
    text: "Excelente atención al cliente, respondieron todas mis dudas por WhatsApp súper rápido. El viaje a Punta Cana fue de ensueño. Gracias Koneex! 🏖️😍",
    likes: 54,
  },
]
